### ISSUE TITLE
OAS 3.1 - The Smaller List of Actualities

### ISSUE THREAD

**Issue by earth2marsh** [OAI/OpenAPI-Specification#2025]
Much progress has been made since The Big List of Possibilities #1466 was created 18+ months ago! Now as we head toward an actual 3.1 release, it is time to collect together all of improvements that may not be backwards compatible. The following is a list of the issues in scope for 3.1, and they should be considered launch blockers until each related PR has been approved and merged into [3.1.0-dev](https://github.com/OAI/OpenAPI-Specification/tree/v3.1.0-dev).

Nb: this is not an exhaustive changelog for v3.1.0.

- [x] Resolve the SemVer ambiguities in #2022 
- [x] Update Schema Objects to JSON Schema Draft 2019-09 #1977 
- [x] Mutual Auth Certificate Support #1004 
- [x] "Scopes" on Security Requirements for schemes other than OAuth2 #1393 #1366
- [x] CSV-serialized form-data arrays #2018 
- [x] Rewording constraints on bodies in HEAD/DELETE PR ~~#1937~~ #2117
- [x] Clarify difference in behavior between $ref inside and outside of schema object #2107
- [x] Post-#1977 knock-on issues #2099

We anticipate at least one release candidate (RC) on the path to the actual release.

Known issues that could be included but might not make the 3.1 release:
- [ ] Overlays #1722

**Comment by handrews** [comment]
As a follow-on to #1977, there needs to be some decision over how `$schema` should be used in the context of OAS.  See issue #2017 which uses PR #2016 (starting point for a schema for OAS 3.1) as an example.

**Comment by andig** [comment]
I‘m totally missing https://github.com/OAI/OpenAPI-Specification/issues/93. It is 6 years old and has community demand. There isn‘t even any comment as to why this would not make it to the long or short list. It also seems to be a low-hanging fruit?

**Comment by MikeRalphson** [comment]
@andig the rationale is here https://github.com/OAI/OpenAPI-Specification/issues/622#issuecomment-545562585

**Comment by andig** [comment]
> @andig the rationale is here [#622 (comment)](https://github.com/OAI/OpenAPI-Specification/issues/622#issuecomment-545562585)

I don‘t fully understand the reasoning of the response, but that‘s fine. Isn‘t it really „wont fix due to...“ then? I feel the message doesn‘t come quite across. 

Forgive me for commenting here, your comment is highly appreciated.
