### ISSUE TITLE
2024 New Year's Cleaning meta-issue

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3516]
***[EDIT: All issues listed here are now tracked via either the [Contributor Guidance project](https://github.com/orgs/OAI/projects/5/views/1) or [Automation & Infrastructure project](https://github.com/orgs/OAI/projects/4/views/1)]***

Towards the end of 2023, a number of folks expressed frustration with the apparently-static state of affairs regarding this repository's issues and PRs.  We've been taking action to fix that, starting with @baywet 's automation efforts and @lornajane 's issue-closing push.  The weekly TDC calls this year have devoted a lot of time to figuring out what to clean up and how to best get it done.

I'm filing this issue to track that work and make it visible to folks who don't join the weekly calls or keep track of the meeting notes.

Governance:

- [ ] Add new members to the @OAI/tsc (this process has [now been started](https://github.com/OAI/OpenAPI-Specification/issues/3496#issuecomment-1898900510))
- [x] #3489 (allows @OAI/openapi-maintainers write access to all but the actual specification documents)
- [ ] #3523 
- [ ] #3524 
- [ ] #3482 
- [ ] #1346 

Build, test, deploy, and automate:

- [ ] #3515 *See also the [list of fixes in question](https://github.com/OAI/OpenAPI-Specification/issues/3487#issuecomment-1885289778)*
- [ ] #3548
- [ ] #3432 
- [ ] #2400
- [x] #3557 
- [ ] https://github.com/OAI/OpenAPI-Specification/issues/151#issuecomment-1556268486 (specifically, add dates to non-dated schemas and define and document the deployment process)
- [x] #3430 
- [ ] #3576

Managing more repos and projects:

- [ ] #1246 (should we split any more non-spec content out of this repo?)
- [ ] #2872 (how to manage SIG-specific specifications)
- [ ] #3561

Planning releases:

- [ ] #3528 
- [ ] #3529 
- [x] #3508 

Managing the backlog:

- [ ] #3509 
- [ ] #3517 
- [ ] #3518 
- [ ] #3527 
- [x] #3533
- [ ] #3581

We may add other process tickets here during this batch of work, but we should close it when we feel like we've reached a new steady state.  I'll assign this to myself to keep the checklist up-to-date and close the issue when appropriate.

**Comment by G1style** [comment]
G1style jump

**Comment by handrews** [comment]
All issues listed here are now tracked in one of the following projects:

* [Contributor Guidance project](https://github.com/orgs/OAI/projects/5/views/1) (for topics requiring TSC agreement)
* [Automation & Infrastructure project](https://github.com/orgs/OAI/projects/4/views/1) (for non-spec, non-policy work that anyone with appropriate GitHub/javascript/automation/etc knowledge is encouraged to pick up)

In #3509, we decided to no longer use meta-issues as a process, and in #3610 we decided to give projects a trial run with these two areas of focus.
