### ISSUE TITLE
[Meta Issue] Specification documentation structure and supporting docs

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#589]
This does not cover what the spec actually support, but rather how the specification documentation itself is provided. This issue will also cover suggestions for supporting docs.

Please don't add comments directly to this issue.

**Comment by fehguy** [comment]
@OAI/tdc please send some feedback for documentation structure

**Comment by RobDolinMS** [comment]
I'll look to @webron for some advice / mentoring on this.

**Comment by RobDolinMS** [comment]
Will look at adding an index / table of contents (ToC): #673

**Comment by fehguy** [comment]
@OAI/tdc here's an inventory of the documentation items for review / examples:

## Metadata
- [ ] OpenAPI Object
- [ ] Info Object
- [ ] Host Object
- [ ] Contact Object
- [ ] License Object
- [ ] Tag Object

- [ ] ## Paths + operations + body parameters
- [ ] Paths Object
- [ ] Path Item Object
- [ ] Operation Object
- [ ] External Documentation Object
- [ ] Parameter Object
- [ ] Request Body Object
- [ ] Items Object

- [ ] ## Responses + payloads
- [ ] Responses Object
- [ ] Response Object
- [ ] Headers Object
- [ ] Example Object
- [ ] Links Object
- [ ] Response Payload Values
- [ ] Header Object
- [ ] Examples Object
- [ ] Reference Object
- [ ] Schema Object
- [ ] XML Object

- [ ] ## Reuse
- [ ] Components Object
- [ ] Definitions Object
- [ ] Parameters Definitions Object
- [ ] Responses Definitions Object

- [ ] ## Security
- [ ] Security Definitions Object
- [ ] Security Scheme Object
- [ ] Scopes Object
- [ ] Security Requirement Object

**Comment by handrews** [comment]
This meta-issue has served its purpose, and any remaining items are being tracked under new labeling now.
