### ISSUE TITLE
[Meta Issue] Documentation cleanup

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#700]
As we work on the spec, we may end up not updating all parts of it completely and before release we need to clean it out. This issue will be used to track known required changes. @OAI/tdc - please edit the this main comment rather than adding requirements as additional comments. Comments added to the ticket will be moved to the main comment and deleted for easier tracking as well.
- [ ] #646 introduced a new host construct that should be used for #604 as well.
- [ ] #812 - new `servers` should be updated instead of `hosts` for `POI``operation`.
- [ ] #812 - need an explanation of what happens when scheme/host/basepath are missing.
- [ ] #818 - define relative URL behavior across the spec (question came up from relative security urls).
- [ ] #807 - look into renaming `apiKey` to a more meaningful name.

**Comment by MikeRalphson** [comment]
Closing as all of the above were merged.
